---
- hosts: all

  become: yes
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Send Slack message when reboot is required
    - name: Send notification message via Slack
      slack:
        token: "{{ slack_token }}"
        msg: "Reboot required on {{ inventory_hostname }}"
      delegate_to: localhost
      #when: reboot_required.stat.exists 