- name: Set timezone to America/Toronto
  become: true
  community.general.timezone:
    name: America/Toronto

- name: Ensure multiple locales exist
  community.general.locale_gen:
    name:
      - en_US.UTF-8
      - fr_CA.UTF-8
    state: present
- name: Set default locale
  command: localectl set-locale LANG=en_US.UTF-8
  when: ansible_distribution == 'Ubuntu'