- name: Update packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Add Fastfetch repository
  ansible.builtin.deb822_repository:
    name: fastfetch
    types:
      - deb
    uris:
      - https://ppa.launchpadcontent.net/zhangsongcui3371/fastfetch/ubuntu
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
    components:
      - main
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xEB65EE19D802F3EB1A13CFE47E2E5CB4D4865F21"
    enabled: true
    state: present
  when:
    - ansible_facts["distribution"] == "Ubuntu"
    - ansible_facts["distribution_version"] is version('26.04', '<')

- name: Install packages
  ansible.builtin.apt:
    name:
      - eza
      - curl
      - gcp
      - fastfetch
      - stow
      - zsh
      - git
      - htop
      - btop
      - iftop
      - zoxide
    update_cache: true
