[master]
192.168.4.101
192.168.4.102
192.168.4.103

[node]
192.168.4.106
192.168.4.107
192.168.4.108

# only required if proxmox_lxc_configure: true
# must contain all proxmox instances that have a master or worker node
# [proxmox]
# 192.168.4.43

[k3s_cluster:children]
master
node
