# Make sure Ansible host has access to these devices
# Good idea to snapshot all machines and deploy uing cloud-init

[servers]
server1 ansible_host=192.168.4.81
server2 ansible_host=192.168.4.82
server3 ansible_host=192.168.4.83

[agents]
agent1 ansible_host=192.168.4.86
agent2 ansible_host=192.168.4.87
agent3 ansible_host=192.168.4.88

[cluster:children]
servers
agents