os: "linux"
arch: "amd64"

talos_version: v1.7.6
talosctl_version: v1.7.6
control_plane_ip: 192.168.4.151

control_plane_2: 192.168.4.152
control_plane_3: 192.168.4.153

worker_1: 192.168.4.161
worker_2: 192.168.4.162
worker_3: 192.168.4.163

config_directory: "/home/{{ ansible_user }}/.talos"
config_file: "/home/{{ ansible_user }}/.talos/talosconfig"

kube_vip_version: "v0.8.0"
vip_interface: eth0
vip: 192.168.3.50

metallb_version: v0.13.12
lb_range: 192.168.4.170-192.168.4.180
lb_pool_name: first-pool

ansible_user: ubuntu
ansible_become: true
ansible_become_method: sudo
