os: "linux"
arch: "amd64"

kube_vip_version: "v0.8.2"
vip_interface: eth0
vip: 192.168.4.100

metallb_version: v0.13.12
lb_range: 192.168.4.111-192.168.4.119
lb_pool_name: first-pool

rke2_version: "v1.30.2+rke2r1"
rke2_install_dir: "/usr/local/bin"
rke2_binary_url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2.linux-amd64"

ansible_user: ubuntu
ansible_become: true
ansible_become_method: sudo
